name: Build-sphinx-docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build HTML
        run: |
          cd docs/
          make html

      - name: Make directory for built documentation
        run: mkdir -p docs/_build/html

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/_build/html
