name: Build-sphinx-docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
           python-version: "3.11"

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          ls -la

      - name: Install dependencies
        run: | 
          pip install -r requirements.txt
          apt-get update && apt-get install -y python3-opencv
          pip install opencv-python
#          pip install opencv-python-headless
#          apt-get update && apt-get install libgl1


      - name: Build HTML
        run: | 
          source venv/bin/activate
          cd docs/
          ls -la
          make html

      - name: Run ghp-import
        run: | 
          source venv/bin/activate
          ghp-import -n -p -f docs/build/html

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
